### ISSUE TITLE
کدام صفحه ویکی پدیا 

### ISSUE THREAD

**Issue by Habib-SJ** [hezardastan-ir/frontend-course#1]
ممنون از دوره ای که راه اندازی کردید.
سوالی داشتم در ابتدای آموزش، در اولین تمرین از ما خواسته بودید که یک صفحه ویکی پدیا طراحی کنیم ولی دقیقا مشخص نکرده بودید کدام صفحه و لینکی هم مرقوم نکرده بودید. شاید هم من متوجه سوال نشدم.
لطفا کمک کنید. این هم تصویر :
 
![1](https://user-images.githubusercontent.com/12404852/101001965-0c601000-3575-11eb-89af-8eb9a9f12485.jpg)

**Comment by theshem** [comment]
@haaaabib سلام. مرسی از پیام‌تون. این لینک متاسفانه خراب شده و درستش می‌کنیم.
‫لینک این صفحه بوده https://en.wikipedia.org/wiki/HTML5
هدف اینجا ساختن کل صفحه نیست، صرفا استفاده از تگ‌هایی که در لینک‌های بالاتر آمده بوده.
